invalid defaultFilter key and value removed
"to" is not a valid eth_newFilter options and causes the following when creating a new event:
Error: [ethjs-rpc] rpc error with payload.
code: -32602
message: 'unknown field `to`, expected one of `fromBlock`, `toBlock`, `address`, `topics`, `limit`'